### ISSUE TITLE
Hij doet het niet.

### ISSUE THREAD

**Issue by sajanssens** [christianspruijt/jwt#1]
Ik heb hem gebruikt op https://github.com/sajanssens/marktplaats. Het werkt niet!

**Comment by christianspruijt** [comment]
`System.in` wordt aangeroepen voordat `JWT.awaitReady();` wordt aangeroepen (en dus voordat de `System.in` wordt omgezet):

```java
private static final Scanner scanner = new Scanner(System.in);

public static void main(String[] args) {
    JWT.awaitReady();
}
```

Kan worden opgelost door `JWT.awaitReady();` aan te roepen voor initialisatie van de `Scanner`:

```java
private static final Scanner scanner;

static {
    JWT.awaitReady();
    scanner = new Scanner(System.in);
}
```
